@bookmark_manager_app_HostAddress = http://localhost:5140/api
// @bookmark_manager_app_HostAddress = http://localhost:8080/api
@cookie = token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlMmIwNjM4MS1lYTY5LTQ0OGItOGIyNC00ZjViNDQ0MWIxNTMiLCJzdWIiOiIxIiwiZW1haWwiOiJkaW1pdHJpLnNpZm91YUBnbWFpbC5jb20iLCJuYW1lIjoiRGltaXRyaSBTaWZvdWEiLCJuYmYiOjE3NzAyOTM0NzIsImV4cCI6MTc3MDI5NzA3MiwiaWF0IjoxNzcwMjkzNDcyLCJpc3MiOiJib29rbWFyay1tYW5hZ2VyLWFwaSIsImF1ZCI6ImJvb2ttYXJrLW1hbmFnZXItY2xpZW50In0.G6jDYo0ZBhVZZjwpkaCQDPYjtGHYUWLPYHWjGP8jidA; max-age=3600; path=/; samesite=strict; httponly

###
GET {{bookmark_manager_app_HostAddress}}/health
Accept: application/json

###
POST {{bookmark_manager_app_HostAddress}}/auth/register
Content-Type: application/json
Accept: application/json

{
    "fullname": "Dimitri Sifoua",
    "email": "dimitri.sifoua@gmail.com",
    "password": "Password123"
}

###
POST {{bookmark_manager_app_HostAddress}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "dimitri.sifoua@gmail.com",
    "password": "Password123"
}

###
POST {{bookmark_manager_app_HostAddress}}/api/auth/logout
Accept: application/json
Cookie: {{cookie}}

###
GET {{bookmark_manager_app_HostAddress}}/bookmarks
Accept: application/json
Cookie: {{cookie}}

###
POST {{bookmark_manager_app_HostAddress}}/bookmarks
Content-Type: application/json
Accept: application/json
Cookie: {{cookie}}

{
    "title": "Claude",
    "url": "https://claude.ai",
    "description": "An AI assistant created by Anthropic that can help with analysis, writing, coding, math, and creative tasks through natural conversation.",
    "tags": [
        "Tools",
        "AI",
        "Learning"  
    ]
}

###
POST {{bookmark_manager_app_HostAddress}}/bookmarks
Content-Type: application/json
Accept: application/json
Cookie: {{cookie}}

{
    "title": "Claude",
    "url": "",
    "description": "An AI assistant created by Anthropic that can help with analysis, writing, coding, math, and creative tasks through natural conversation.",
    "tags": [
        "Tools",
        "AI",
        "Learning"
    ]
}

###
DELETE {{bookmark_manager_app_HostAddress}}/bookmarks/1
Accept: application/json
Cookie: {{cookie}}

###
GET {{bookmark_manager_app_HostAddress}}/bookmarks/1
Accept: application/json
Cookie: {{cookie}}

###
PATCH {{bookmark_manager_app_HostAddress}}/bookmarks/1/pin
Accept: application/json
Cookie: {{cookie}}

###
POST {{bookmark_manager_app_HostAddress}}/visits
Content-Type: application/json
Accept: application/json
Cookie: {{cookie}}

{
    "bookmarkId": 1,
    "visitTime": "2026-01-31T19:49:19.462909+00:00"
}

###
GET {{bookmark_manager_app_HostAddress}}/tags
Accept: application/json
Cookie: {{cookie}}
