@bookmark_manager_app_HostAddress = http://localhost:5140

GET {{bookmark_manager_app_HostAddress}}/
Accept: application/json

###

GET {{bookmark_manager_app_HostAddress}}/user
Accept: application/json

###
