@bookmark_manager_app_HostAddress = http://localhost:5140

### Get all users
GET {{bookmark_manager_app_HostAddress}}/api/users
Accept: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1MzE4MGQwZS02NTQyLTRlMzAtOTAwNS0yZThlNzk0ZmUwMDUiLCJzdWIiOiJkaW1pdHJpLnNpZm91YUBnbWFpbC5jb20iLCJuYW1lIjoiRGltaXRyaSBTaWZvdWEiLCJuYmYiOjE3Njk1MzIwNTMsImV4cCI6MTc2OTUzNTY1MywiaWF0IjoxNzY5NTMyMDUzLCJpc3MiOiJCb29rbWFya01hbmFnZXJBcGkiLCJhdWQiOiJCb29rbWFya01hbmFnZXJBcGlVc2VycyJ9.5H5OA6Hz6zozkQ4kLYR_QHnmJV5-xN8-_pQRb_oFD5o; max-age=3600; path=/; samesite=strict; httponly