@bookmark_manager_app_HostAddress = http://localhost:5140

### Get all users
GET {{bookmark_manager_app_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyMGViY2I0ZC0wYjhlLTQ4ZjUtYjY2Yy04YWQ4NGYwMTM5ZjMiLCJzdWIiOiJkaW1pdHJpLnNpZm91YUBnbWFpbC5jb20iLCJuYmYiOjE3NjkzMzc4OTUsImV4cCI6MTc2OTM0MTQ5NSwiaWF0IjoxNzY5MzM3ODk1LCJpc3MiOiJCb29rbWFya01hbmFnZXJBcGkiLCJhdWQiOiJCb29rbWFya01hbmFnZXJBcGlVc2VycyJ9.Cl3Zr27SvKXkBEvxsYNrAZWjixRbMiA6TsN2qBRKgks