@bookmark_manager_app_HostAddress = http://localhost:5140

### Login Dimitri
POST {{bookmark_manager_app_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "dimitri.sifoua@gmail.com",
    "password": "Password123"
}

### Login Dimitri with a wrong password
POST {{bookmark_manager_app_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "dimitri.sifoua@gmail.com",
    "password": "Password1234"
}

### Login a non existing user
POST {{bookmark_manager_app_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "not.exist@mail.com",
    "password": "Password123"
}