@bookmark_manager_app_HostAddress = http://localhost:5140

### Register Elsa
POST {{bookmark_manager_app_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "fullname": "Elsa Sifoua",
  "email": "elsa.sifoua@gmail.com",
  "password": "Password123"
}

### Register an existing user
POST {{bookmark_manager_app_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "fullname": "Dimitri",
    "email": "dimitri.sifoua@gmail.com",
    "password": "Password123"
}

### Register a user with empty fields
POST {{bookmark_manager_app_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "fullname": " ",
    "email": " ",
    "password": ""
}

### Register a user with an invalid email
POST {{bookmark_manager_app_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "fullname": "John Doe",
    "email": "john.doe@mail.com",
    "password": "Password123"
}

### Register a user non matching passwords
POST {{bookmark_manager_app_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "fullname": "John Doe",
    "email": "john.doe@mail.com",
    "password": "Password123"
}