@bookmark_manager_app_HostAddress = http://localhost:5140/api/bookmark-tags

### Retrieve all tags
GET {{bookmark_manager_app_HostAddress}}
Accept: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkYTc0NGMyNi0zY2I1LTRmZDItYmJkMC1jMGUwYmQzOTFhZTYiLCJzdWIiOiIxIiwiZW1haWwiOiJkaW1pdHJpLnNpZm91YUBnbWFpbC5jb20iLCJuYW1lIjoiRGltaXRyaSBTaWZvdWEiLCJuYmYiOjE3Njk2NjY1NDksImV4cCI6MTc2OTY3MDE0OSwiaWF0IjoxNzY5NjY2NTQ5LCJpc3MiOiJCb29rbWFya01hbmFnZXJBcGkiLCJhdWQiOiJCb29rbWFya01hbmFnZXJBcGlVc2VycyJ9.55f_JDtAr7nuFsbWJhW4FSBEBwJSw14qcyAhpjScVRM; max-age=3600; path=/; samesite=strict; httponly
