@bookmark_manager_app_HostAddress = http://localhost:5140/api/bookmarks

### Get all bookmarks
GET {{bookmark_manager_app_HostAddress}}
Accept: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMWE3YjY0ZS05MDY4LTRkZmItYWUxNy1kNTE2YjdjNmUwODAiLCJzdWIiOiIxIiwiZW1haWwiOiJkaW1pdHJpLnNpZm91YUBnbWFpbC5jb20iLCJuYW1lIjoiRGltaXRyaSBTaWZvdWEiLCJuYmYiOjE3Njk1MzU3ODAsImV4cCI6MTc2OTUzOTM4MCwiaWF0IjoxNzY5NTM1NzgwLCJpc3MiOiJCb29rbWFya01hbmFnZXJBcGkiLCJhdWQiOiJCb29rbWFya01hbmFnZXJBcGlVc2VycyJ9.CQNHR5x1sVcjBwoJbUBKXFdUw_y-2Rt-LFvDvoyR0bQ; max-age=3600; path=/; samesite=strict; httponly
